[package]
name = "nexus-codec"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nexus-common = { path = "../nexus-common" }
nexus-capture = { path = "../nexus-capture" }
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true
bytes.workspace = true
