[package]
name = "nexus-transport"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nexus-common = { path = "../nexus-common" }
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true
tokio.workspace = true
quinn.workspace = true
rustls.workspace = true
anyhow.workspace = true
rcgen.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
nexus-protocol = { path = "../nexus-protocol" }
prost.workspace = true
tracing-subscriber.workspace = true
